// Generated by `zfa package create-plugin` — value codec contract.
import 'package:test/test.dart';
import 'package:zuraffa_inappwebview/zuraffa_inappwebview.dart';

void main() {
  test('i32 encodes to an int', () {
    expect(InappwebviewI32(42).encode(), 42);
  });

  test('i64 encodes to a decimal string and decodes back', () {
    final value = InappwebviewI64(BigInt.parse('9007199254740993'));

    expect(value.encode(), '9007199254740993');
    expect(
      (InappwebviewValue.decode(value.encode()) as InappwebviewI64).value,
      BigInt.parse('9007199254740993'),
    );
  });

  test('f64 encodes to a double', () {
    expect(InappwebviewF64(0.5).encode(), 0.5);
  });
}
